# Generated by Django 4.1 on 2022-09-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1)),
                ('seleccion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='selecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.CharField(max_length=20)),
                ('jug_nombre', models.CharField(max_length=20)),
                ('jug_apellido', models.CharField(max_length=20)),
                ('posicion', models.CharField(max_length=20)),
            ],
        ),
    ]
