# Generated by Django 4.1.1 on 2022-10-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataMundial', '0003_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModelBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
